### PR TITLE
Opacity support

### PR DESCRIPTION
**Pull request by Tuxilero**
Adding -O argument that specify opacity of drawed lines.

### CODE REVIEW

**Comment by bk138** [comment]
Nice. But can you make it -o and --opacity to keep in line with the other arguments? Also, do you mind implementing a setting for the contxt menu?

**Comment by Tuxilero** [comment]
This should do it :)

**Comment by bk138** [comment]
Well when the README is in sync with the code, yes ; -)

**Comment by Tuxilero** [comment]
Done

**Comment by bk138** [comment]
Thaaanks!

**Pull request merged**
