### PR TITLE
Add pen color selection

### LINKED ISSUE #71: color selector
Changing colors is currently a little cumbersome (edit the config file, restart gromit-mpx).
This is especially problematic when you want to use gromit-mpx to make design decisions by comparing a color against another (e.g on top of an image), without having to open an image editor.

Having a color selector (similar to gcolor2) to change the main color would make it a lot easier.
The way I see it implemented is as a popup window which you could open from the menu.

### PR DESCRIPTION
**Pull request by serpilliere**
This PR adds the feature of choosing color from the menu.
Fix #71

### CODE REVIEW

**Comment by bk138** [comment]
Thanks for the contribution! This does not work for me yet, though: The dialog pops up, I can choose a colour, but the painting colour stays red... Any idea what to do/look at?

**Comment by serpilliere** [comment]
Oh! Interesting.
Can you add a `printf("test\n");` at line 602, just after the:
```C
      gdk_cairo_set_source_rgba(data->default_pen->paint_ctx, data->default_pen->paint_color);
```

**Comment by bk138** [comment]
Yeah, that fires.

**Comment by serpilliere** [comment]
Thank you for the feed back @bk138 !
This means I missed something in setting the color back to the pen...

**Comment by bk138** [comment]
Might this relate to differing gtk versions?

**Comment by serpilliere** [comment]
I just realized that using the default branch, I cannot erase using right or middle button.
This may be linked to this (I tested on arch linux)

**Comment by serpilliere** [comment]
Ok, I manage to reproduce the bug: I forgot to set a configuration file. This explains that I wasn't able  to erase using right click.
I am debugging the branch now I have reproduced the bug

**Comment by serpilliere** [comment]
Hi!
It seems that the different tools are stored in a hash table, and the way to get them is to know their shortcut :cry: 
So I added a pointer to the current tool, which is update each time the user select a different tool.
Now, the color may change the current tool !
The color is *not* stored back to the config file.

**Comment by bk138** [comment]
Some of this can be used for #110, so I'd like to keep a reference once work starts on that. Closing as this PR will not be merged as-is, but code will be re-used.

**Comment by serpilliere** [comment]
Great!

**Pull request closed without merging**
